language: php
php:
    - 5.4
service:
    - postgresql
before_install:
    - cp ./travis/config.travis.pgsql.php ./config/config.php
    - chmod -R a+x ./travis/scripts
    - phpenv config-add ./travis/myconfig.ini
install:
    - ./travis/scripts/postgresql-setup.sh
    - ./travis/scripts/simplesamlphp-setup.sh
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias ssl headers
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo cat /etc/postgresql/9.1/main/pg_hba.conf
  - sudo sed -i "s/host    all             all             127.0.0.1\/32            trust/host    all             all             127.0.0.1\/32            md5/" /etc/postgresql/9.1/main/pg_hba.conf
  - sudo sed -i "s/host    all             all             ::1\/128                 trust/host    all             all             ::1\/128                 md5/" /etc/postgresql/9.1/main/pg_hba.conf
  - sudo cat /etc/postgresql/9.1/main/pg_hba.conf
  - sudo sed -i "s/NameVirtualHost \*:80/# NameVirtualHost \*:80/" /etc/apache2/ports.conf
  - sudo sed -i "s/Listen 80/# Listen 80/" /etc/apache2/ports.conf
  - sudo cat /etc/apache2/apache2.conf
  - sudo cat /etc/apache2/ports.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/certs/filesender_test.key -out /etc/ssl/certs/filesender_test.crt -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"
  - sudo cp -f travis/config.travis.apache2.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo ls /var/log/
  - sudo ls /var/log/apache2
  - sudo cat /etc/init.d/apache2
  - sudo ls -la /usr/sbin/apache*
  - sudo cat /var/log/apache2/error.log
  - sudo sed -i "s/exit \$ERROR/cat \/var\/log\/apache2\/error.log/" /usr/sbin/apache2ctl
  - sudo cat /usr/sbin/apache2ctl
  - sudo service postgresql restart
  - sudo service apache2 restart

  - sudo cat /var/log/apache2/error.log
after_failure:


script:
    - ls -la /etc/postgresql/
    #- phpunit --configuration ./unittests/config_tests_filesender.xml
notifications:
    email: false