language: php
php:
    - 5.4
services:
    - postgresql
before_install:
    - cp ./travis/config.travis.php ./config/config.php
    - chmod a+x ./travis/scripts/postgresql-setup.sh
script:
    - ./travis/scripts/postgresql-setup.sh
notifications:
    email:
        recipients:
            - emiel@codebridge.nl
        on_success: [always]
        on_failure: [always]