language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
script:
    - ls
    - cd unittests
    - launcher.sh -c config_tests_filesender.xml -ts FileSenderUtilities
    - cd
notifications:
    - email: true