language: php
php:
    - 5.4
service:
    - postgresql
before_install:
    - cp ./travis/config.travis.pgsql.php ./config/config.php
    - chmod a+x ./travis/scripts/postgresql-setup.sh
before_script:
    - ./travis/scripts/postgresql-setup.sh
script:
    - phpunit --configuration ./unittests/config_tests_filesender.xml
notifications:
    email:
        recipients:
            - emiel@codebridge.nl
        on_success: [always]
        on_failure: [always]