language: php
php:
    - 5.4
service:
    - postgresql
before_install:
    - cp ./travis/config.travis.pgsql.php ./config/config.php
    - chmod -R a+x ./travis/scripts
    - phpenv config-add ./travis/myconfig.ini
install:
    - ./travis/scripts/postgresql-setup.sh
    - ./travis/scripts/simplesamlphp-setup.sh
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias ssl headers
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo cat /etc/postgresql/9.1/main/pg_hba.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f travis/config.travis.apache2.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
script:
    - ls -la /etc/postgresql/
    #- phpunit --configuration ./unittests/config_tests_filesender.xml
notifications:
    email: false